### ISSUE TITLE
i cannot filter any data

### ISSUE THREAD

**Issue by sakarimov** [GothenburgBitFactory/tasklib#114]
i want to filter data in with filter ```tw.tasks.filter("status:completed")```
but i get this error, where am i wrong?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 464, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 481, in __getitem__
    self._result_cache = list(self)
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 471, in __len__
    self._result_cache = list(self.__iter__())
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 476, in __iter__
    self._result_cache = self._execute()
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/task.py", line 508, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/backends.py", line 334, in filter_tasks
    for line in self.execute_command(args):
  File "/home/sulthan/.local/lib/python3.10/site-packages/tasklib/backends.py", line 297, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.backends.TaskWarriorException: TASKDATA override: /home/sulthan/.task
Configuration override rc.confirmation=no
Configuration override rc.dependency.confirmation=no
Configuration override rc.recurrence.confirmation=no
Configuration override rc.json.array=off
Configuration override rc.bulk=0
Configuration override rc.data.location=/home/sulthan/.task
Unable to find report that matches 'status:completed'.
Command used: task rc.confirmation=no rc.dependency.confirmation=no rc.recurrence.confirmation=no rc.json.array=off rc.bulk=0 rc.data.location=/home/sulthan/.task export status:completed
```

**Comment by arozans** [comment]
I have the same issue. Tasklib works correctly with older TaskWarrior versions, before 2.6.0. 

I think this is the same issue as this one: https://github.com/ralphbean/taskw/pull/152

It is really a pity that 'official' taskwarrior library is not supporting latest release after so many months.
